name: 02 - Workflow Events

on: 
  pull_request:
  workflow_dispatch:


jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Event-Name
        run: |
          echo "Event name: ${{ github.event_name }}"
