name: 04 - Using-Actions-With-ReatApplicaion

on: push

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v4
      - name: List all directories 
        run: ls -ltr