name: 05 - 2 - Filter-activity-types

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Closed PR Event
        run: echo "Running whenever PR is closed."
