name: 07 - Expressions

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] Display Event Name'
        if: ${{ github.event_name == 'push' }}
        run: "echo \"This is a test message from the event: ${{ github.event_name }}\""
      - name: '[debug] Display Debug Input'
        if: inputs.debug && github.ref == 'refs/heads/main'
        run: "echo \"This is a test message from the debug: ${{ inputs.debug }}\""
